on:
  push:
    branches:
      - main

jobs:
  dns:
    name: Update DNS Records
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: CompeyDev/setup-rokit@v0.1.2

      - name: Retrieve previous version of cname.luau
        run: git show HEAD~1:cname.luau > cname-old.luau

      - name: Update DNS Records
        run: lute scripts/update.luau
        env:
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
